### ISSUE TITLE
训练没有效果

### ISSUE THREAD

**Issue by imsyu** [ZhangYuef/Comdefend_tensorflow#1]
您好,我将test_mode设成0和7训练了两次,用的都是默认参数,但是Accuracy都为0,我看到放上的效果图里Accuracy也很低,是因为test用的图片太少还是我对Accuracy的理解有错误,希望您能解答一下,谢谢!

**Comment by ZhangYuef** [comment]
这里的`Accuracy`就是指分类的准确率，确实加入resnet block后的效果不如原文中的方法得到的`Accuracy`值高。
最后的训练结果为0可能是因为迭代次数不够多，可以把每次的结果输出看一下。

**Comment by imsyu** [comment]
您好，我按照您的建议增大了迭代次数，虽然今天因为电脑电源短路了没完成设定的训练，但是也训练了有200到300个epoch，据我观察到的结果，只有几次test的结果不为0，其余都为0，想请教一下问题出在哪里，参数的设置需要更改吗，您当时训练了多久才达到论文里的效果，谢谢！我使用的test_mode=0，也就是论文里的模型。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhangYuefeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月22日(星期二) 凌晨0:46
收件人:&nbsp;"ZhangYuef/Comdefend_tensorflow"<Comdefend_tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"shiyu"<im.syu@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhangYuef/Comdefend_tensorflow] 训练没有效果 (#1)




Closed #1.

**Comment by ZhangYuef** [comment]
是不是因为模型训练数据？我在放出来的代码里只引了十张图片作为示例，您可以看一下原文里对训练数据的要求。

**Comment by imsyu** [comment]
您的意思是test用的图像太少了吗，论文中是在cifar10和mnist的测试集上实验的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhangYuefeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月22日(星期二) 凌晨1:13
收件人:&nbsp;"ZhangYuef/Comdefend_tensorflow"<Comdefend_tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"shiyu"<im.syu@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhangYuef/Comdefend_tensorflow] 训练没有效果 (#1)




是不是因为模型训练数据？我在放出来的代码里只引了十张图片作为示例，您可以看一下原文里对训练数据的要求。

**Comment by ZhangYuef** [comment]
是的，我这里放出来的实验结果和原文一样是在1000张ImageNet数据集上做的分类任务。

**Comment by imsyu** [comment]
好的，非常感谢，我会按照这个重新测试一遍




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhangYuefeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月22日(星期二) 凌晨1:28
收件人:&nbsp;"ZhangYuef/Comdefend_tensorflow"<Comdefend_tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"shiyu"<im.syu@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhangYuef/Comdefend_tensorflow] 训练没有效果 (#1)




是的，我这里放出来的实验结果和原文一样是在1000张ImageNet数据集上做的分类任务。

**Comment by ZhangYuef** [comment]
不谢不谢，加油：）
