### ISSUE TITLE
训练Loss不收敛

### ISSUE THREAD

**Issue by RainVerse** [ZhangYuef/Comdefend_tensorflow#2]
我尝试用pytorch复现了论文的网络（不带残差模块），但由于原作者的代码没有提供训练过程的实现代码，因此参考了您的代码，但在训练中Loss一直没能收敛，因此想问您几个问题：

1.最后网络收敛时Loss大概的值为多少？我在训练过程中Loss一直保持在1左右不收敛。
2.在cifar上训练多少epoch比较合适？作者在原文中给出的是30epoch，而您的代码中则是3，是因为您的loss在第三轮左右就接近收敛了吗？

**Comment by ZhangYuef** [comment]
> 我尝试用pytorch复现了论文的网络（不带残差模块），但由于原作者的代码没有提供训练过程的实现代码，因此参考了您的代码，但在训练中Loss一直没能收敛，因此想问您几个问题：
> 
> 1.最后网络收敛时Loss大概的值为多少？我在训练过程中Loss一直保持在1左右不收敛。
> 2.在cifar上训练多少epoch比较合适？作者在原文中给出的是30epoch，而您的代码中则是3，是因为您的loss在第三轮左右就接近收敛了吗？

您好，关于您的两个问题：
1. 网络最后收敛时具体loss值我没有记录，不好意思
2. 网络最后我们在训练的时候差不多1个epoch（7500 interations）就收敛了，所以我们最后只训练了三轮就进行了测试

不好意思回复的有点晚了，希望有帮助: )
