### ISSUE TITLE
您好我看了comdefend的论文自己训练了cafir的代码准确率低

### ISSUE THREAD

**Issue by yearep7** [ZhangYuef/Comdefend_tensorflow#3]
训练完之后准确率和您图标的结果一样只有百分之十几我想问这样不影响之后的结果吗，能得到论文里的数据吗，准确率这么低的原因是什么能不能解答一下疑惑

**Comment by ZhangYuef** [comment]
> 训练完之后准确率和您图标的结果一样只有百分之十几我想问这样不影响之后的结果吗，能得到论文里的数据吗，准确率这么低的原因是什么能不能解答一下疑惑

根据我们当时的尝试，得到结论：原文结果可复现。 我们展示的结果图效果不够好有一部分原因是我们新增的模块反而影响了原文方法中的效果（也可能是训练方法有待改进）。

您想复现原文结果的话，建议严格按照原始论文中的描述搭建网络并训练。

**Comment by yearep7** [comment]
1.我使用的是test mode 0，看代码应该是和原论文一致的
2. 即使效果达不到原论文的效果，为什么按着git上的图片（paper蓝色曲线）和我做出来的结果，准确率都成下降趋势
3. 还有就是，如果testmode0和原论文有不一致，是否可以说明下哪部分做了修改？
能不能解答一下谢谢您

**Comment by ZhangYuef** [comment]
关于1和3，我很抱歉我现在没有时间再去回顾原文，但我猜测效果没有达到原文的原因之一是和2中的问题有相关性：准确率出现_下降_趋势是正常的，论文中所汇报的结果是取某一个效果最优的 epoch 点上对应的模型。
